twig:
    form_themes: ['form/tailwind_2_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        isCheckout: false
        storeConfig: '@App\Twig\Global\Core\StoreConfig'
        categoryTree: '@App\Twig\Global\Catalog\CategoryTree'
        quickMenuTree: '@App\Twig\Global\Catalog\QuickMenuTree'

when@test:
    twig:
        strict_variables: true
