twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        showDivider: false
        categoryTree: '@App\Twig\Global\Catalog\CategoryTree'

when@test:
    twig:
        strict_variables: true
