before_script:
  - docker info

stages:
  - build_php
  - build_nginx

build_php:
  stage: build_php
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker build -f ./docker/php/Dockerfile -t $CI_REGISTRY_IMAGE/frontend-php ./
    - docker push $CI_REGISTRY_IMAGE/frontend-php
  artifacts:
    paths:
      - CI_PROJECT_DIR/build/

build_nginx:
  stage: build_nginx
  when: on_success
  dependencies:
    - build_php
  image: docker
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker build -f ./docker/nginx/Dockerfile -t $CI_REGISTRY_IMAGE/frontend-nginx ./
    - docker push $CI_REGISTRY_IMAGE/frontend-nginx
