before_script:
  - docker info

build:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - cp $DOTENV_STAGE $CI_PROJECT_DIR/.env
    - docker build -f ./docker/php/Dockerfile -t $CI_REGISTRY_IMAGE/frontend-php ./
    - docker push $CI_REGISTRY_IMAGE/frontend-php
#    - docker build -f ./docker/nginx/Dockerfile -t $CI_REGISTRY_IMAGE/frontend-nginx ./
#    - docker push $CI_REGISTRY_IMAGE/frontend-nginx