before_script:
  - docker info

build:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -f ./docker/Dockerfile -t $CI_REGISTRY_IMAGE/frontend ./
    - docker push $CI_REGISTRY_IMAGE/frontend