parameters:
  redis_server_url: '%env(resolve:REDIS_SERVER_URL)%'
  postcode_api:
    api:
      api_key: '%env(resolve:POSTCODE_API_API_KEY)%'
      base_url: '%env(resolve:POSTCODE_API_BASE_URL)%'
  mage_client:
    api:
      base_url: '%env(resolve:MAGE_API_BASE_URL)%'
      default_headers:
        verify: true
  imaginary_client:
    enabled: '%env(resolve:IMAGINARY_ENABLED)%'
    base_url: '%env(resolve:IMAGINARY_BASE_URL)%'
    app_url: '%env(resolve:IMAGINARY_APP_URL)%'
  imgproxy:
    key: '%env(resolve:IMGPROXY_KEY)%'
    salt: '%env(resolve:IMGPROXY_SALT)%'
    base_url: '%env(resolve:IMGPROXY_BASE_URL)%'

  when@prod:
    api:
      default_headers: [ ]
    imaginary_client:
      enabled: true

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Redis:
    class: Redis
    calls:
      - connect:
          - '%env(REDIS_SESSION_HOST)%'
          - '%env(int:REDIS_SESSION_PORT)%'
          - '%env(int:REDIS_SESSION_DB)%'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@Redis'
      - { 'ttl': 86400 }

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  Symfony\Component\HttpKernel\EventListener\RouterListener:
    arguments:
      - '@App\Routing\MagentoRouteMatcher'

  App\Routing\MagentoRouteMatcher:
    arguments:
      - '@router.default'

  App\Cache\Adapter\RedisAdapter:
    arguments:
      - '@service_container'

  App\Service\Api\Magento\Http\:
    resource: '../src/Service/Api/Magento/Http'
    arguments:
      - '@service_container'

  App\Service\Api\Postcode\:
    resource: '../src/Service/Api/Postcode'
    arguments:
      - '@service_container'

  App\Service\Imaginary\Http\:
    resource: '../src/Service/Imaginary/Http'
    arguments:
      - '@logger'
      - '@service_container'

  App\Service\ImgProxy\:
    resource: '../src/Service/ImgProxy'
    arguments:
      - '@logger'
      - '@service_container'
